### PR TITLE
fix: detect errors after comments in no-multiple-h1 and require-alt-text

### LINKED ISSUE #464: Bug: `no-multiple-h1` and `require-alt-text` miss errors after a HTML comment is closed
### Environment

ESLint version: 9.31.0
@eslint/markdown version: 7.0.0
Node version: 22.15.0
npm version: 10.9.2
Operating System: Ubuntu 24.04

### Which language are you using?

gfm

### What did you do?

<details>
<summary>Configuration</summary>

```
import { defineConfig } from "eslint/config";
import markdown from "@eslint/markdown";

export default defineConfig({
  files: ["**/*.md"],
  plugins: { markdown },
  language: "markdown/gfm",
  rules: {
    "markdown/no-multiple-h1": "error",
    "markdown/require-alt-text": "error",
  },
});

```
</details>

```md
# Heading 1

<h1>Reported</h1>
<!-- --> <h1>Not reported</h1>

---

<img src="reported.png" />
<!-- --> <img src="not-reported.png" />
```

### What did you expect to happen?

With [`no-multiple-h1: error`](https://github.com/eslint/markdown/blob/56eb0ee4d1ffd81fe4eb7cec9dda27e35939842f/docs/rules/no-multiple-h1.md) the substring `<h1>Not reported</h1>` should be reported.

With [`require-alt-text: error`](https://github.com/eslint/markdown/blob/56eb0ee4d1ffd81fe4eb7cec9dda27e35939842f/docs/rules/require-alt-text.md) the substring `` should be reported.

### What actually happened?

Neither is reported.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-cttfryej?file=eslint.config.js,markdown.md&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

For both this is due to the regular subexpression `(?<!<!--[\s\S]*?)<`, which does not end after the closing `-->`.

- https://github.com/eslint/markdown/blob/56eb0ee4d1ffd81fe4eb7cec9dda27e35939842f/src/rules/no-multiple-h1.js#L27
- https://github.com/eslint/markdown/blob/56eb0ee4d1ffd81fe4eb7cec9dda27e35939842f/src/rules/require-alt-text.js#L27

### PR DESCRIPTION
**Pull request by TKDev7**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

This pull request fixes a bug where the `no-multiple-h1` and `require-alt-text` rules failed to report errors for headings and images that appear after a closed HTML comment in Markdown files. 

#### What changes did you make? (Give an overview)

- Added a utility function to strip HTML comments from Markdown content before running rule checks.
- Updated the `no-multiple-h1` rule to ensure that `<h1>` tags after HTML comments are correctly detected and reported.
- Updated the `require-alt-text` rule to ensure that `` tags after HTML comments are correctly detected and reported.
- Added tests to confirm that both rules now report errors for content following closed HTML comments.

#### Related Issues

Fixes #464

### CODE REVIEW

**Comment by snitin315** [comment]
> Is this issue ready for a pull request? Issues that are ready for pull requests have the accepted label, which indicates that the team has agreed to accept a pull request. Please do not send pull requests for issues that have not been marked as accepted.

Hi @TKDev7, thanks for the PR! Going forward, please wait for the team to accept the issue before beginning any work. Kindly make sure to read and follow our [contributing guidelines.](https://eslint.org/docs/latest/contribute/work-on-issue#issue-labels)

File: src/rules/no-multiple-h1.js [hunk 1]
```diff
@@ -110,8 +110,10 @@ export default {
 			},
 
 			html(node) {
+				const text = stripHtmlComments(node.value);
+
 				let match;
-				while ((match = h1TagPattern.exec(node.value)) !== null) {
+				while ((match = h1TagPattern.exec(text)) !== null) {
```
Comment (snitin315) [inline src/rules/no-multiple-h1.js:101]: Now we are matching with regular expression twice, wouldn't this make the rule slower?

Comment (TKDev7) [reply src/rules/no-multiple-h1.js:101]: Unfortunately, I can't think of a way around this. We do something similar in `no-missing-link-fragments` as well.

**Comment by nzakas** [comment]
@lumirlumir I don't think it's worth putting PRs on hold pending #483. Let's get the functionality working and we can always go back and refactor later.

File: src/util.js
Comment (lumirlumir) [inline src/util.js:1]: Nitpick: 

Would it be possible to group regular expressions with regular expressions and utility functions with utility functions?

I understand that `htmlCommentPattern` is related to `stripHtmlComments`, but I think grouping them separately would make things a bit clearer.

File: src/util.js [hunk 2]
```diff
@@ -37,3 +37,19 @@ export function findOffsets(text, offset) {
...
+ * Regular expression to match HTML comments, including multiline comments.
+ */
+export const htmlCommentPattern = /<!--[\s\S]*?-->/gu;
+
+/**
+ * Remove all HTML comments from a string.
+ * @param {string} value The string to remove HTML comments from.
+ * @returns {string} The string with HTML comments removed.
+ */
+export function stripHtmlComments(value) {
```
Comment (lumirlumir) [inline src/util.js:70]: Test:

Can we add a few brief test cases to https://github.com/eslint/markdown/blob/main/tests/util.test.js?

File: src/util.js [hunk 3]
```diff
@@ -37,3 +37,19 @@ export function findOffsets(text, offset) {
...
+	return value.replace(htmlCommentPattern, match =>
+		match.replace(/[^\n]/gu, " "),
+	);
```
Comment (lumirlumir) [inline src/util.js:73]: Question:

In the `no-missing-link-fragments` rule, we've only removed HTML comments as shown below:

https://github.com/eslint/markdown/blob/1fdbd62fe62e2c14bfaf53100c6abf7da85edfeb/src/rules/no-missing-link-fragments.js#L140-L143

Is there a particular reason for using additional processing like `match.replace(/[^\n]/gu, " ")` after stripping HTML comments?

**Review by lumirlumir — CHANGES_REQUESTED** [review]

File: src/util.js
Comment (nzakas) [reply src/util.js:1]: @lumirlumir we generally don't leave nitpicks on PR reviews. If you feel that this is important to address, then you can definitely mention it. If not, then you can just leave it off.

File: src/util.js (hunk 3 above)
Comment (TKDev7) [reply src/util.js:73]: I've switched to ultrahtml, so I'm marking these conversations as resolved.

File: src/util.js
Comment (lumirlumir) [reply src/util.js:1]: @nzakas 

Thank you for pointing that out. I’ll be sure to keep it in mind going forward.

**Review by lumirlumir — COMMENTED** [review]
Sorry for the confusion, @TKDev7, and thank you for taking a look at the `ultrahtml` approach.

Since we're not fully ready to migrate to the `ultrahtml` approach yet, I can't confidently say that using `ultrahtml` here is the right move.

As [we've decided to extract only the necessary logic from `ultrahtml`](https://github.com/eslint/markdown/issues/483#issuecomment-3113642874), I'd like to hear some opinions from the @eslint/eslint-team on whether using `ultrahtml` logic here is a good direction moving forward.

File: src/util.js (hunk 2 above)
Comment (TKDev7) [reply src/util.js:70]: I think the current rule tests will cover our needs for `stripHtmlComments()`, especially since the function itself will be removed in the refactor.

File: src/util.js (hunk 3 above)
Comment (TKDev7) [reply src/util.js:73]: > Is there a particular reason for using additional processing like match.replace(/[^\n]/gu, " ") after stripping HTML comments?

Yes. The `match.replace(/[^\n]/gu, " ")` preserves newlines for accurate error reporting. We need this to calculate correct line/column offsets. The `no-missing-link-fragments` rule doesn't require this because it reports errors on link nodes, not HTML nodes.

**Review by lumirlumir — APPROVED** [review]
LGTM, thanks.

Would like @snitin315 to verify the changes before merging.

**Review by snitin315 — APPROVED** [review]
