### PR TITLE
fix: fenced-code-language highlights only relevant parts

### LINKED ISSUE #476: Rule Change: Highlight fences only in fenced-code-language rule reports
### What rule do you want to change?

fenced-code-language

### What change do you want to make?

Highlight fences only in fenced-code-language rule report

### How do you think the change should be implemented?

Other

### Example code

\

\```js
const message = "Hello, world!";
console.log(message);
\```

### What does the rule currently do for this code?

Currently, when a violation occurs (e.g., missing language or disallowed language), the rule reports the entire code block.

### What will the rule do after it's changed?

After this change, the rule will only highlight the relevant parts of the code block for a violation.
- For a **missing language** error, it will highlight only the **opening fences**.
- For a **disallowed language** error, it will highlight the **opening fence and the specified language**.

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

This change will make the reported locations more precise and similar to how markdownlint highlight issues, making it easier for developers to pinpoint the exact source of the problem without distracting from the entire code content.

### PR DESCRIPTION
**Pull request by TKDev7**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

This pull request aims to enhance the clarity and precision of error reporting for the fenced-code-language rule. Previously, rule violations would highlight the entire code block, making it difficult to pinpoint the exact issue. This change ensures that only the relevant parts of the code are highlighted, improving the developer experience.

#### What changes did you make? (Give an overview)

I've modified the fenced-code-language rule to provide more targeted highlighting for violations:

- For missing language errors, only the opening fences (e.g., ```) of the code block are now highlighted.
- For disallowed language errors, it will highlight the opening fence and the specified language.

#### Related Issues

Fixes #476

### CODE REVIEW

File: src/rules/fenced-code-language.js [hunk 1]
```diff
@@ -90,7 +99,16 @@ export default {
...
 					context.report({
-						loc: node.position,
+						loc: {
+							start: node.position.start,
+							end: {
+								line: node.position.start.line,
+								column:
+									sourceCode.lines[
+										node.position.start.line - 1
+									].length + 1,
```
Comment (JoshuaKGoldberg) [inline src/rules/fenced-code-language.js]: [Bug] Any meta text attached to the code block will also be captured by this. But meta text isn't what's relevant.

````md
```js foo
````

````md
```js filename="src/index.js"
````

Proposal: how about limiting the range to just the <code>\`\`\`</code>, as well as the language if disallowed?

File: tests/rules/fenced-code-language.test.js
Comment (JoshuaKGoldberg) [inline tests/rules/fenced-code-language.test.js:1]: [Testing] Regardless of whether my other comment proposal is taken on, I think testing for the meta case should be added. The rule's decision to report or not report on meta text is going to now be intentional behavior.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
A solid start! 🙌

File: src/rules/fenced-code-language.js (hunk 1 above)
Comment (TKDev7) [reply src/rules/fenced-code-language.js]: I went back and forth on this and decided to follow Markdownlint by highlighting the entire info string.

Comment (JoshuaKGoldberg) [reply src/rules/fenced-code-language.js]: Other than keeping to Markdownlint's precedent, was there a motivation for this way?

Comment (TKDev7) [reply src/rules/fenced-code-language.js]: That was the main reason. However, I decided to go with your approach to avoid capturing meta text.
